### PR TITLE
fix: normalize file paths for Windows

### PR DESCRIPTION
**Pull request by Lehoczky**
When using `importPT` with `path.resolve` on Windows, the `\` characters are not escaped, leading to "failed to resolve import" errors.

This PR addresses this issue.

image

### CODE REVIEW

**Comment by vanozi** [comment]
can this PR be merged? I also encouter the same issue

**Comment by Msalati** [comment]
Hi, This PR needs to be merged, I'm also encountering the same issue. @mertsincan

**Comment by Lehoczky** [comment]
Since the primevue team don't seem to be interested in external contributions (they ignore even very small PRs for weeks, sometimes a month in their other repositories as well), I have a workaround for you guys that you can use in your codebase.

First, install [pathe](https://github.com/unjs/pathe):

```sh
npm i -D pathe
```

Then do the path normalization in your own `nuxt.config.ts`:

```ts
import { resolve } from 'pathe';

export default defineNuxtConfig({
 primevue: {
        options: {
            unstyled: true
        },
        // pathe will automatically change Windows-style `\` to `/`
        importPT: { from: resolve(__dirname, './presets/lara/') }
    },
})
```

I must say though, that it's a shame they don't engage with the community. I've seen issues and other good PRs being ignored for really long times. Primevue would be a great library, but this is very discouraging.

**Comment by Msalati** [comment]
> Since the primevue team don't seem to be interested in external contributions (they ignore even very small PRs for weeks, sometimes a month in their other repositories as well), I have a workaround for you guys that you can use in your codebase.
> 
> First, install [pathe](https://github.com/unjs/pathe):
> 
> ```shell
> npm i -D pathe
> ```
> 
> Then do the path normalization in your own `nuxt.config.ts`:
> 
> ```ts
> import { resolve } from 'pathe';
> 
> export default defineNuxtConfig({
>    primevue: {
>         options: {
>             unstyled: true
>         },
>         // pathe will automatically change Windows-style `\` to `/` and therefore solves this issue
>         importPT: { from: resolve(__dirname, './presets/lara/') }
>     },
> })
> ```
> 
> I must say though, that it's a shame they don't engage with the community. I've seen issues and other good PRs being ignored for really long times. Primevue would be a great library, but this is very discouraging.

Thank you so much for your help 🙏

**Pull request merged**
